pipeline {
    agent any

    stages {
        stage('Docker Build') {
            steps {
                sh 'docker build -t todoapp .'
            }
        }
        stage('Docker Run') {
            steps {
                sh 'docker run -u root -p 53000:8080 todoapp'
            }
        }
    }
}