pipeline {
    agent any

    stages {
        stage('Docker Build') {
            steps {
                sh 'docker build -t todoapp .'
            }
        }
        stage('Docker Run') {
            steps {
                sh 'docker run --rm -u root -p 8080:8080 -v jenkins-data:/var/jenkins_home -v $(which docker):/usr/bin/docker -v /var/run/docker.sock:/var/run/docker.sock -v "$HOME":/home jenkinsci/blueocean
'
            }
        }
    }
}